nodes:
- input.visual:
   source: custom_data/inspection
- model.mtcnn
- draw.bbox
- custom_nodes.model.casting_classifier
- output.csv_writer:
   stats_to_track: ["filename", "pred_label", "pred_score"]
   file_path: casting_predictions.csv
   logging_interval: 0 
#- output.media_writer:
#    output_dir: './output'
