nodes:
- input.visual:
    source: 0
#- custom model node
- augment.brightness:
    beta: 50
- augment.contrast:
    alpha: 1.0
- dabble.fps
- draw.bbox
- draw.legend:
    show: ['fps']
- output.screen
- output.csv_writer