# List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.

# Receive filename or img as input.
# filename - str
# img - np.ndarray
input: ["filename", "img"]

# Output bboxed, bbox_scores, bbox_labels 
# bboxes - numpy.ndarray
# bbox_scores - numpy.ndarray
# bbox_labels - numpy.ndarray
output: ["bboxes", "bbox_scores", "bbox_labels"]

# Optional configs depending on node
threshold: 0.9 
