# List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.

# Receive filename or img as input.
# filename - str
# img - np.ndarray
input: ["img"]

# Output pred_label, pred_score
# pred_label - str
# pred_score - float
output: ["pred_label", "pred_score"]

weights_parent_dir: weights
class_label_map: {0: 'square', 1: 'round'}
#class_label_map : {0: "triangle", 1: "heart", 2: "diamond", 3: "round", 4: "oblong", 5: "oval", 6: "square"}
# Optional configs depending on node
#threshold: 0.9 
